## load libs

In [3]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
from process_images import *
from pystripe.core import *
import matplotlib.pyplot as plt
def plot_images(img_list: List[ndarray], img_labels: List[str], vmax: int):
    if len(img_list) == 1:
        plt.figure(figsize=(20, 20))
        plt.imshow(img_list[0], cmap='gray', vmin=0, vmax=vmax)
        plt.title(img_labels[0])
    else:
        fig, axes = plt.subplots(nrows=1, ncols=len(img_list), figsize=(20, 20))
        for idx, (im, label) in enumerate(zip(img_list, img_labels)):
            axes[idx].imshow(im, cmap='gray', vmin=0, vmax=vmax)
            axes[idx].set_title(label)
    plt.tight_layout()
    plt.show()

In [ ]:
from parallel_image_processor import *
tsv_volume = TSVVolume.load(r'E:\20230510_13_34_13_SM230308_05_LS_15x_800z_MIP_stitched\Ex_488_Em_525_MIP_xml_import_step_5.xml')
shape: Tuple[int, int, int] = tsv_volume.volume.shape  # shape is in z y x format
img = tsv_volume.imread(
    VExtent(
        tsv_volume.volume.x0, tsv_volume.volume.x1,
        tsv_volume.volume.y0, tsv_volume.volume.y1,
        tsv_volume.volume.z0 + shape[0]//2, tsv_volume.volume.z0 + shape[0]//2 + 1),
    tsv_volume.dtype)[0]
parallel_image_processor(
    source=TSVVolume.load(r'/data/20230419_17_34_03_SM221011_06_LS_15x_800z_stitched/Ex_488_Em_525_xml_import_step_5.xml'),
    destination=r"/data/20230419_17_34_03_SM221011_06_LS_15x_800z_stitched/Ex_488_Em_525_tif",
    fun=process_img,
    kwargs={'bleach_correction_frequency': 0.0005, 'bleach_correction_max_method': False, 'bleach_correction_y_slice_max': None, 'threshold': None, 'sigma': (4000.0, 4000.0), 'bidirectional': True, 'lightsheet': False, 'percentile': 0.25, 'rotate': 90, 'convert_to_8bit': False, 'bit_shift_to_right': 8, 'tile_size': (39220, 28056), 'd_type': 'uint16', "verbose": True},
    source_voxel=(0.8, 0.4, 0.4),
    target_voxel=20,
    max_processors=1
)

In [ ]:
def get_layer(
    index: int,          # layer of image requested
    image: ndarray,      # 3-D image (use TifStack.as_3d_numpy())
    plane = "xy",        # must be "xy", "yx", "xz", "zx", "yz", "zy"
    img_format = "zyx",  # xyz in some order
):
    # guards
    if plane not in {"xy", "yx", "xz", "zx", "yz", "zy"} or img_format not in {"zyx", "zxy", "yxz", "yzx", "xyz", "xzy"}:
        print(f"Invalid plane selected in get_layer().  Plane: {plane}, Layer: {index}, Img_format: {img_format}\nReturning to caller...")
        return None

    # get the layer
    if 'x' not in plane:   sub = img_format.index('x')
    elif 'y' not in plane: sub = img_format.index('y')
    elif 'z' not in plane: sub = img_format.index('z')

    if sub == 0:   layer_image = image[index, :, :]
    elif sub == 1: layer_image = image[:, index, :]
    elif sub == 2: layer_image = image[:, :, index]

    # if plane is flipped compared to image format, return the transpose.
    if plane not in (img_format[:sub] + img_format[sub + 1:]):
        return layer_image.transpose()
    return layer_image

# run to rotate images
from os import makedirs

######## CHANGE THESE ########
cha1_path = "D:/BMAP/Brain 4/cha1"
cha2_path = "D:/BMAP/Brain 4/cha2"
cha3_path = "D:/BMAP/Brain 4/cha3"
# set to None if nothing to convert

##############################
if cha1_path:
    makedirs(cha1_path + "_zx", exist_ok=True)
    makedirs(cha1_path + "_zy", exist_ok=True)
    stack1 = TifStack(cha1_path).as_3d_numpy()
    for i in range(stack1.shape[1]):
        imwrite(cha1_path + "_zx/" + str(i + 1) + ".tif", get_layer(i, stack1, "zx"))
    for i in range(stack1.shape[2]):
        imwrite(cha1_path + "_zy/" + str(i + 1) + ".tif", get_layer(i, stack1, "zy"))
if cha2_path:
    makedirs(cha2_path + "_zx", exist_ok=True)
    makedirs(cha2_path + "_zy", exist_ok=True)
    stack2 = TifStack(cha2_path).as_3d_numpy()
    for i in range(stack2.shape[1]):
        imwrite(cha2_path + "_zx/" + str(i + 1) + ".tif", get_layer(i, stack2, "zx"))
    for i in range(stack2.shape[2]):
        imwrite(cha2_path + "_zy/" + str(i + 1) + ".tif", get_layer(i, stack2, "zy"))
if cha3_path:
    makedirs(cha3_path + "_zx", exist_ok=True)
    makedirs(cha3_path + "_zy", exist_ok=True)
    stack3 = TifStack(cha3_path).as_3d_numpy()
    for i in range(stack3.shape[1]):
        imwrite(cha3_path + "_zx/" + str(i + 1) + ".tif", get_layer(i, stack3, "zx"))
    for i in range(stack3.shape[2]):
        imwrite(cha3_path + "_zy/" + str(i + 1) + ".tif", get_layer(i, stack3, "zy"))
print("Operation Completed")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def plot_data(file_path:str, title:str, label1:str, label2:str):
    with open(file_path, "r") as file:
        line = file.readline()

        x_offset = [0]
        y_offset = [0]

        while line:
            if "Skipped" in line:
                x_offset.append(0)
                y_offset.append(0)
                line = file.readline()
                continue
            s = line.split(",")
            x_offset.append(float(s[-2][:-1]))
            line = file.readline()
            s = line.split(",")
            y_offset.append(float(s[-2][:-1]))
            line = file.readline()
            # skip last line
            line = file.readline()

        plt.plot(range(len(x_offset)), x_offset, label=label1)
        plt.plot(range(len(y_offset)), y_offset, label=label2)
        plt.title(title)
        plt.xlabel("Layer index")
        plt.ylabel("Units")
        plt.ylim((-20, 20))
        plt.legend()
        plt.show()

plot_data("D:/BMAP/Brain 4/offsets/zy_matrices_im12.txt", "Image alignment offsets of Images 1 and 2 from zy-slices", "z-offset", "y-offset")
plot_data("D:/BMAP/Brain 4/offsets/zy_matrices_im13.txt", "Image alignment offsets of Images 1 and 3 from zy-slices", "z-offset", "y-offset")
plot_data("D:/BMAP/Brain 4/offsets/zx_matrices_im12.txt", "Image alignment offsets of Images 1 and 2 from zx-slices", "z-offset", "x-offset")
plot_data("D:/BMAP/Brain 4/offsets/zx_matrices_im13.txt", "Image alignment offsets of Images 1 and 3 from zx-slices", "z-offset", "x-offset")
plot_data("D:/BMAP/Brain 4/offsets/xy_matrices_im12.txt", "Image alignment offsets of Images 1 and 2 from xy-slices", "x-offset", "y-offset")
plot_data("D:/BMAP/Brain 4/offsets/xy_matrices_im13.txt", "Image alignment offsets of Images 1 and 3 from xy-slices", "x-offset", "y-offset")

In [18]:
from pathlib import Path
from align_images import get_layer
from numpy import min, max, uint8, zeros_like, ndarray, multiply

def write_to_file(images: list[ndarray], filepath: Path):
    filepath.mkdir(parents=True, exist_ok=True)
    for n, image in enumerate(images):
        local = filepath / f'cha{n}'
        local.mkdir(parents=True, exist_ok=True)
        for layer in range(image.shape[0]):
            path = local.absolute() / (str(layer) + ".tif")
            imwrite(path, get_layer(layer, image, "yx"))
        print("wrote to file")
        
# written by ChatGPT
def normalize_array_inplace(arr: ndarray):
    min_val = min(arr)
    max_val = max(arr)

    arr -= min_val
    arr /= (max_val - min_val)

    # Scale the values to be between 0 and 255
    arr *= 255
    arr.astype(uint8, copy=False)
    

# multiplies two 2d-ndarrays, saving solution in arr1 instead of allocating more memory
def mult_in_place(arr1, arr2):
    for r in range(arr1.shape[0]):
        for c in range(arr1.shape[1]):
            arr1[r][c] *= arr2[r][c]
 
 
def get_borders(img: ndarray, copy=False):
    print("get_borders")
    mask = zeros_like(img)
    for ind in range(img.shape[0]):
        print(f'layer {ind}')
        mask[ind] = get_img_mask(img[ind], otsu_threshold(img[ind]))
    multiply(img, mask, out=img)
    
    

In [4]:
from align_images import align_all_images, resize_arrays, get_borders
from supplements.tifstack import TifStack

cha1 = TifStack("C:/Users/ajan/Pictures/cha0").as_3d_numpy()
cha2 = TifStack("C:/Users/ajan/Pictures/cha1").as_3d_numpy()
cha3 = TifStack("C:/Users/ajan/Pictures/cha2").as_3d_numpy()
output_path = Path("D:/aligned_images/align_test")
max_iterations = 50

print("Images loaded")

# make arrays the same size
channels = resize_arrays([cha1, cha2, cha3])

print("Images resized")
# print("test")
# for i in channels: print(i.shape)


for img in channels:
    get_borders(img)    

print("got borders")

# align images
alignments, residuals = align_all_images(channels, verbose=True, make_copy=False)

# normalize images and convert to uint8
for channel in channels: normalize_array_inplace(channel)

print("Images normalized")

write_to_file(channels, output_path)

print("Done!")
# print("Alignment: ", end='')
# print(alignments)
# print("Residuals: ", end='')
# print(residuals) 

Images loaded
Images resized
threshold 52
got borders... displaying images
threshold 75
got borders... displaying images
threshold 71
got borders... displaying images
got borders
Loaded images.
Resized shapes: (1, 411, 438)
Iteration 0
downsampling factor for transformation_matrix 1
[[ 1.    0.   -8.68]
 [ 0.    1.   -0.76]
 [ 0.    0.    1.  ]]
downsampling factor for transformation_matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
downsampling factor for transformation_matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4
0
0
Iteration 1
downsampling factor for transformation_matrix 1
[[ 1.    0.   -8.64]
 [ 0.    1.   -4.43]
 [ 0.    0.    1.  ]]
downsampling factor for transformation_matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
downsampling factor for transformation_matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4
-2
0
Iteration 2
downsampling factor for transformation_matrix 1
[[ 1.    0.    3.57]
 [ 0.    1.   -7.77]
 [ 0.    0.    1.  ]]
downsampling factor for transformation_matrix 1
[[1

error: OpenCV(4.8.1) D:\bld\libopencv_1698890390607\work\modules\video\src\ecc.cpp:589: error: (-7:Iterations do not converge) The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped in function 'cv::findTransformECC'


* try using mask for better edge detection
* Sobel operator -> mask -> align

In [1]:
# convert stacks to .ims
import os
dir_name = "D:/aligned_images/20230825_SM230601_06_LS_15x_800z_B6/orig_aligned"

os.system(f'python convert.py -i "{dir_name}/cha0" -o "{dir_name}/cha0.ims" -dx 10 -dy 10 -dz 10')
os.system(f'python convert.py -i "{dir_name}/cha1" -o "{dir_name}/cha1.ims" -dx 10 -dy 10 -dz 10')
os.system(f'python convert.py -i "{dir_name}/cha2" -o "{dir_name}/cha2.ims" -dx 10 -dy 10 -dz 10')

0

In [12]:
!python align_images.py C:/Users/ajan/Pictures/ D:\aligned_images\align_test
!echo done

Loading images...
Images loaded
['C:/Users/ajan/Pictures/cha0', 'C:/Users/ajan/Pictures/cha1', 'C:/Users/ajan/Pictures/cha2']
Figure(640x480)
Figure(640x480)
Figure(640x480)
Resizing images...
Images resized
Aligning images... (this may take a while)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Figure(640x480)
[[[157 159 160 ... 178 190 160]
  [160 151 153 ... 175 180 151]
  [169 152 154 ... 162 136 128]
  ...
  [ 48  51  54 ... 112 104 106]
  [ 41  54  65 ... 118 116 118]
  [ 57  60  62 ... 111 117 124]]]
Figure(640x480)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Figure(640x480)
Images normalized
Writing to file
Wrote to file
Alignments:


Operation completed.
done


In [22]:
from align_images import resize_arrays

from os import system
from matplotlib.pyplot import imshow, show

pad_only = False
generate_ims = False
dx, dy, dz = 0, 0, 0
filepaths = ["C:/Users/ajan/Pictures/cha0", "C:/Users/ajan/Pictures/cha1","C:/Users/ajan/Pictures/cha2"]
output_file = f"C:/Users/ajan/Pictures/align_test"
# Image Processing --------------------------------------------------------------------
print("Loading images...")
count = 0
try:
    cha1 = TifStack(filepaths[0]).as_3d_numpy()
    count = 1
    cha2 = TifStack(filepaths[1]).as_3d_numpy()
    count = 2
    cha3 = TifStack(filepaths[2]).as_3d_numpy()
    print("Images loaded")
except Exception:
    print(f"Error: Invalid TifStack found at {filepaths[count]}")
    exit(1)

output_path = Path(output_file)
output_path.mkdir(parents=True, exist_ok=True)

print(filepaths)

imshow(cha1[0])
show(block=True)
imshow(cha2[0])
show(block=True)
imshow(cha3[0])
show(block=True)

print("Resizing images...")

channels = resize_arrays([cha1, cha2, cha3])
print("Images resized")

# normalize images and convert to uint8
# print("Normalizing images")
# for channel in channels: normalize_array_inplace(channel)



if not pad_only:
    print("Aligning images... (this may take a while)")
    # TODO: FIX THIS
    for i in range(len(channels)):
        # channels[i] *= (channels[i] > percentile(channels[i], 80))  # set all pixels below threshold to zero. (weeds out noise along edges)
        # get_borders(channels[i])
        # channels[i] = sobel(channels[i])

        print(channels[i])
        imshow(channels[i][0, :, :])
        show()


    # # align images
    # alignments, residuals = align_all_images(channels, max_iter=max_iterations, verbose=False, make_copy=False)
    # print("Images aligned")


print("Images normalized")

print("Writing to file")
write_to_file(channels, output_path)
print("Wrote to file")

if generate_ims:
    print("Generating .ims files")
    system(f'python convert.py -i "{output_path}/cha0" -o "{output_path}/cha0.ims" -dx {dx} -dy {dy} -dz {dz}')
    system(f'python convert.py -i "{output_path}/cha1" -o "{output_path}/cha1.ims" -dx {dx} -dy {dy} -dz {dz}')
    system(f'python convert.py -i "{output_path}/cha2" -o "{output_path}/cha2.ims" -dx {dx} -dy {dy} -dz {dz}')
    print(".ims files created")

print("Alignments:")
# print(alignments)
print("\n\nOperation completed.")

AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)

In [9]:
from numpy import zeros, ones, pad, uint8
from align_images import write_to_file, roll_pad
from pathlib import Path

cube = zeros((126, 126, 126), dtype=uint8)
cube = pad(cube, 1, mode='constant', constant_values=255)

cha0 = pad(cube, 64)
cha1 = pad(cube, 64)
cha2 = pad(cube, 64)

roll_pad(cha1, 1, axis=0)
roll_pad(cha1, 2, axis=1)
roll_pad(cha1, 3, axis=2)

roll_pad(cha2, -3, axis=0)
roll_pad(cha2, -2, axis=1)
roll_pad(cha2, -1, axis=2)


path = Path("D:/aligned_images/cube_test/upright_borders")

write_to_file([cha0, cha1, cha2], path, verbose=True)
    


wrote to file
wrote to file
wrote to file
